apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    upstream appcluster {
     server 192.168.1.2:31050;
     server 192.168.1.3:31050;
     keepalive 1024;
    }
