apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    tier: backend
spec:
  selector:
    app: app1
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 31050