Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "kubernetes-worker2.riajul.com"
    virtualbox__intnet: true
  config.vm.network "private_network", ip: "192.168.1.3"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 1
  end
  
end