apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    tier: backend
spec:
  selector:
    app: app2
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 31050